
version: '3'
services:
  backend:
    image: pabbasi/pld_backend:dev-latest

    restart: unless-stopped
    container_name: backend_api
    networks:
      - inside-network

    command: >
      sh -c "python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"

    volumes:
#      - ./Backend/PLD_API/:/usr/src/app/
      - ./Backend/PLD_API/db.sqlite3:/usr/src/app/db.sqlite3
      - ./Backend/PLD_API/media:/usr/src/app/media

networks:
  inside-network:


#version: '3.8'
#
#services:
#  mediamtx:
#    image: bluenviron/mediamtx:latest-ffmpeg
#    container_name: mediamtx
#    restart: unless-stopped
#    environment:
#      - MTX_RTSPTRANSPORTS=tcp
#      - MTX_WEBRTCADDITIONALHOSTS=192.168.244.209  # Replace with your actual IP if needed
#    ports:
#      - "8554:8554"   # RTSP
#      - "1935:1935"   # RTMP
#      - "8888:8888"   # WebRTC
#      - "8889:8889"   # API
#      - "8890:8890/udp"  # WebRTC UDP
#      - "8189:8189/udp"  # WebRTC UDP
#    volumes:
#      - ./mediamtx.yml:/mediamtx.yml  # Mount custom config file (optional)



#services:
#  mediamtx:
#    image: bluenviron/mediamtx:latest-ffmpeg
#    container_name: mediamtx
#    network_mode: host  # Recommended
#    volumes:
#      - ./mediamtx.yml:/mediamtx.yml
#    restart: unless-stopped


