
version: '3'
services:
  backend:
    image: pabbasi/pld_backend:dev-latest

    restart: unless-stopped
    container_name: backend_api
    networks:
      - inside-network

    command: >
      sh -c "python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"

    volumes:
#      - ./Backend/PLD_API/:/usr/src/app/
      - ./Backend/PLD_API/db.sqlite3:/usr/src/app/db.sqlite3

networks:
  inside-network: