# Generated by Django 5.1.3 on 2024-12-05 19:26

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('plate', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=64, null=True)),
                ('name_and_model', models.CharField(max_length=128, null=True)),
                ('owner_first_name', models.CharField(max_length=128, null=True)),
                ('owner_last_name', models.CharField(max_length=128, null=True)),
                ('owner_username', models.CharField(max_length=128, null=True)),
                ('is_allways_permitted', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('plate', 'owner_username')},
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('enter', 'ورودی'), ('exit', 'خروجی')], default='enter', max_length=20)),
                ('permission_needed', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='api.place')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.place')),
                ('security_agent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='security',
            field=models.ManyToManyField(related_name='secured_gates', through='api.SecurityAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TemporaryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField(auto_now_add=True)),
                ('to_time', models.DateTimeField()),
                ('description', models.TextField(default='بدون توضیحات')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.automobile')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.auto_traffic_image)),
                ('time', models.DateTimeField()),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.automobile')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gate')),
                ('security_agent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traffics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.AddField(
            model_name='gate',
            name='traffics',
            field=models.ManyToManyField(related_name='passed_gates', through='api.Traffic', to='api.automobile'),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together={('name', 'type')},
        ),
    ]
