# Generated by Django 5.1.3 on 2024-12-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_place_automobile_gate_securityassignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityassignment',
            options={'ordering': ('-start_time',)},
        ),
    ]
