# Generated by Django 5.1.3 on 2024-12-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_securityassignment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.automobile'),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='gate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.gate'),
        ),
    ]
