# Generated by Django 5.1.3 on 2024-12-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_traffic_automobile_alter_traffic_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='name_and_model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='owner_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
