# Generated by Django 5.1.3 on 2024-12-23 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_automobile_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarypermission',
            name='from_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
