# Generated by Django 5.1.3 on 2024-12-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_temporarypermission_from_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarypermission',
            name='granted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='granted_perms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
