# Generated by Django 5.1.3 on 2024-12-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_temporarypermission_granted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='defaults/default_profile_image.jpg', help_text='image for profile of user', null=True, upload_to='profile_pics/', verbose_name='Profile Image'),
        ),
    ]
