# Generated by Django 5.1.3 on 2025-01-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_securityassignment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
