# Generated by Django 5.1.3 on 2025-02-04 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_place_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='permitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='security_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='traffics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
