"""
Django settings for PLD_API project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-aly!!7jg!6nwsh*ve5u^q5(h^*x2!a*2d@$pcx@pcupbo8w#c)')

SECURE_SSL_CONFIGURED = bool(int(os.environ.get('DJANGO_SECURE_SSL_CONFIGURED', 0)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DJANGO_DEBUG', 1)))

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

INTERNAL_IPS = ['127.0.0.1', 'localhost', '192.168.236.114']

DOMAIN = 'localhost'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "djoser",
    "debug_toolbar",
    "api.apps.ApiConfig",
    'corsheaders',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
]


AUTH_USER_MODEL = 'api.User'  # custom user model for this project


ROOT_URLCONF = 'PLD_API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PLD_API.wsgi.application'
ASGI_APPLICATION = 'PLD_API.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


CONN_MAX_AGE = os.environ.get('DJANGO_CONN_MAX_AGE', 0)
CONN_MAX_AGE = None if CONN_MAX_AGE == "None" else int(CONN_MAX_AGE)

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# MySQL for production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', 'pld_database'),  # Database name
        'USER': os.environ.get('MYSQL_USER', 'pld_user'),  # Database user
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'pld_password'),  # Database password
        'HOST': os.environ.get('MYSQL_HOST', 'localhost'),  # The MySQL service name in Docker
        'PORT': os.environ.get('MYSQL_PORT', '3306'),  # Default MySQL port
        'OPTIONS': {
            'charset': 'utf8mb4',  # Use UTF-8 with full Unicode support
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOG_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)  # Ensure the logs directory exists

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file_debug": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "debug.log"),
            "formatter": "verbose",
        },
        "file_errors": {
            "level": "WARNING",  # Logs warnings and above
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "errors.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file_debug", "file_errors"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file_errors"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


REST_FRAMEWORK = {

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
    ,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    'PAGE_SIZE': 50
}


DJOSER = {
    'LOGIN_FIELD': 'username',
    'SERIALIZERS': {
        'user_create': 'api.serializers.UserCreateSerializer',
        'user': 'api.serializers.UserSerializer',
        'current_user': 'api.serializers.CurrentUserSerializer',
        'set_password': 'api.serializers.SetPasswordSerializer',
    },
    'PERMISSIONS': {
        'user_create': ['api.permissions.IsManagerUser',],
        'user_delete': ['api.permissions.IsManagerUser',],
        'set_password': ['api.permissions.IsManagerUser',],
    },
    'DISABLE_ENDPOINTS': [
        'reset_username', 'reset_password',
    ]

}


SIMPLE_JWT = {
    'UPDATE_LAST_LOGIN': False,

    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    "AUTH_HEADER_TYPES": ("JWT",),

    "TOKEN_OBTAIN_SERIALIZER": "api.serializers.TokenObtainPairSerializer",
}

# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = ['http://127.0.0.1:8000'] + os.environ.get('DJANGO_CORS_ALLOWED_ORIGINS', 'http://localhost:8000').split(',')
CORS_ALLOW_HEADERS = (
    *default_headers,
    'Content-Type',
    'Authorization',
    "x-requested-with",
    'x-ai-auth',
)
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = SECURE_SSL_CONFIGURED
CSRF_COOKIE_SECURE = SECURE_SSL_CONFIGURED
SECURE_SSL_REDIRECT = SECURE_SSL_CONFIGURED

SESSION_SAVE_EVERY_REQUEST = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
] + os.environ.get('CSRF_ALLOWED_ORIGINS', "http://localhost").split(',')

DATETIME_FORMAT = '%Y/%m/%d-%H:%M:%S'
DATETIME_INPUT_FORMATS = ['%Y/%m/%d-%H:%M:%S', ]

AI_MODEL_AUTH_TOKEN = "ai_auth_token"


# Configure channel layers (using in-memory backend for development)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.environ.get('REDIS_HOST', 'localhost'), 6379)],
        },
    },
}
